// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Dt3S--x8JdkSP8C9JXz7fPyYWCLO1gQ',
    appId: '1:32429475995:web:148d681ba0784af888de3e',
    messagingSenderId: '32429475995',
    projectId: 'mpii-rigelapp',
    authDomain: 'mpii-rigelapp.firebaseapp.com',
    storageBucket: 'mpii-rigelapp.appspot.com',
    measurementId: 'G-CYQ4WR871L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa92sTcRo0flQig6zz9EmpsOmTQ5sTa2w',
    appId: '1:32429475995:android:5b0dab398662e08e88de3e',
    messagingSenderId: '32429475995',
    projectId: 'mpii-rigelapp',
    storageBucket: 'mpii-rigelapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxi-haqkpYswBxUZT_LonzRcf9MF9Yueo',
    appId: '1:32429475995:ios:f164c994c462edff88de3e',
    messagingSenderId: '32429475995',
    projectId: 'mpii-rigelapp',
    storageBucket: 'mpii-rigelapp.appspot.com',
    iosClientId: '32429475995-sn4rkfonfl7d5icclgf8nnu1mior5jom.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProductsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxi-haqkpYswBxUZT_LonzRcf9MF9Yueo',
    appId: '1:32429475995:ios:f164c994c462edff88de3e',
    messagingSenderId: '32429475995',
    projectId: 'mpii-rigelapp',
    storageBucket: 'mpii-rigelapp.appspot.com',
    iosClientId: '32429475995-sn4rkfonfl7d5icclgf8nnu1mior5jom.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProductsFlutter',
  );
}
